config/routes.rb
Chat::Application.routes.draw do
  match '/logout' => 'session#destroy', via: [:get, :post]
  match '/auth/:provider/callback' => 'session#create', via: [:get, :post]
  match '/auth/failure' => 'session#failure', via: [:get, :post]
  resources :messages
  root :to => "messages#index"
  get '/stream' => 'messages#stream'
  post '/comment' => 'messages#comment'
  get '/chat_history' => 'messages#history'
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
require 'streamer/sse'
class MessagesController < ApplicationController
	include ActionController::Live

   def index
	   @message = Message.new
	   @messages = Message.all(order: "created_at desc", limit: 30)
	   @user_name = user_name
	   @signed_in = is_signed_in?
   end

   def history
	   @message = Message.new
	   @messages = Message.paginate(page: params[:page], per_page: 30).order("created_at desc")
	   @user_name = user_name
   end

   def create
	   @m = Message.new(message_params)
	   @m.from_user = user_name
	   if @m.save
		   respond_to do |format|
		   	format.html { redirect_to root_url }
		   	format.js
		   end
	   else
		   respond_to do |format|
		   	format.html { render :index }
		   	format.js
		   end
	   end
   end

  def stream
	  @messages = Message.all(order: "created_at desc", limit: 30)
	  response.headers['Content-Type'] = 'text/event-stream'
	  sse = Streamer::SSE.new(response.stream)
	  sse.write(@messages.to_json)
=begin
	  redis = Redis.new
	  redis.subscribe('messages.create') do |on|
		  on.message do |event, data|
			  sse.write(data, event: 'messages.create')
		  end
	  end
=end
	  render nothing: true
  rescue IOError
	  # Client disconnected
  ensure
#	  redis.quit
	  sse.close
  end


  def comment
	  response.headers['Content-Type'] = 'text/javascript'
	  @message = params.require(:message).permit(:name, :content)
	  $redis.publish('messages.create', @message.to_json)
=begin
	  start_serve do |sse_client|
		  sse_client.send_sse sse
		  sse_client.send_sse_hash data: "Shehzan"
	  end
=end
  end

  private
  def sse(object, options = {})
	  (options.map{|k,v| "#{k}: #{v}" } << "data: #{JSON.dump object}".join("\n") + "\n\n")
  end

  def message_params
	  params.require(:message).permit(:from_user, :text)
  end

	def is_signed_in?
	  @signed_in = (cookies.permanent.signed[:authenticated] == true)
	end

	def user_name
	  @user_name = cookies.permanent.signed[:user_name]
	end

	def authenticate
		unless is_signed_in?
			redirect_to login_path
		end
	end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
	  cookies.permanent.signed[:authenticated] = true
	  cookies.permanent.signed[:user_name] = request.env['omniauth.auth']['extra']['raw_info']['login']
	  redirect_to root_url
  end

  def destroy
	  cookies.delete :authenticated
	  debugger
	  cookies.delete :user_name
	  redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Chat", root_path, :class => 'brand' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Chat" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Chat" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "messages", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "messages" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
	  	<%= debug params %>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/messages/_form.html.erb
<div class="message_form">
	<% if @signed_in %>
		<%= simple_form_for @message, remote: true do |f| %>
			<h4><%= @user_name %></h4>
			<%= f.input :text %>
			<%= f.button :submit %>
		<% end %>
		<%= link_to "Sign out", logout_path %>
	<% else %>
		<%= link_to "Sign in using Github (Make sure you're logged into the right github account)", '/auth/github' %>
	<% end %>
</div>

app/views/messages/create.js.erb
<% if @m.errors.messages.empty? %>
	insertNewMessage("<%= escape_javascript @m.to_json.html_safe %>");
	$('#message_text').val("");
<% else %>
	alert("You have a blank field!");
<% end %>

app/views/messages/history.html.erb
<div class="">
	<%= render 'form' %>
	<div class="chats">
		<% @messages.each do |m| %>
			<div class="message message_<%= m.id %>">
				<h4><%= m.from_user %></h4>
				<p><%= m.text %></p>
			</div>
		<% end %>
	</div>
	<%= will_paginate @posts %>
</div>

app/views/messages/index.html.erb
<div class="">
	<%= render 'form' %>
	<div class="chats">
		<% @messages.each do |m| %>
			<div class="message message_<%= m.id %>">
				<h4><%= m.from_user %></h4>
				<p><%= m.text %></p>
			</div>
		<% end %>
	</div>
	<%= link_to 'View all Messages', chat_history_path %>
</div>

app/views/messages/stream.html.erb
<h1>HI</h1>